---
# Build and push image
- name: Create mesos-slave Dockerfile
  template: src=mesos-slave-dockerfile.j2 dest=roles/ansible-coreos-mesos-slave/docker/docker-mesos-slave/Dockerfile
  tags:
    - configuration

- name: Build mesos-slave image
  docker_image: path="roles/ansible-coreos-mesos-slave/docker/docker-mesos-slave" name="{{ mesosslave_image_name }}" state="build"
  tags:
    - docker
    - docker_build

- name: Push mesos-slave image to repo
  shell: "docker push {{ mesosslave_image_name }}"
  tags:
    - docker
    - docker_push

# Create required fleet unit files
- name: Create Units directory
  file: path=units state=directory mode=0755
  tags:
    - configuration

# Get number of coreos machines
- name: Gather fleet machines info
  get_coreos_machines: tunnel={{ fleet_endpoint }}
  register: fleetctl_hosts
  tags:
    - configuration

- name: Create mesos-slave Units
  template: src=mesos-slave.x.service.j2 dest=units/mesos-slave.{{ item }}.service
  with_sequence: count={{ fleetctl_hosts.count }}
  tags:
    - configuration

# Submit units to fleet
- name: Submit mesos-slave units
  shell: fleetctl --tunnel {{ fleet_endpoint }} submit units/mesos-slave.{{ item }}.service
  with_sequence: count={{ fleetctl_hosts.count }}
  tags:
    - fleet
    - fleet_submit

# Start units via fleet
- name: Start mesos-slave units
  shell: sleep 5 && fleetctl --tunnel {{ fleet_endpoint }} start units/mesos-slave.{{ item }}.service
  with_sequence: count={{ fleetctl_hosts.count }}
  tags:
    - fleet
    - fleet_start
