- hosts: coreos
  gather_facts: no
  sudo: True
  roles:
  - { role: ansible-coreos }

- hosts: local
  gather_facts: no
  roles:
  - { role: ansible-coreos-registry, registry_hostname: "dockerregistry" }
  - { role: ansible-coreos-zookeeper, zookeeper_instances_number: "3" }
